import assert from "node:assert/strict";
import {createRequest,actOnRequest,canRead,validateDraft,requiredDocuments,validateAttachments,REGIONS,type Actor,type Draft} from "../src/lib/requests/model";
import {SERVICES} from "../src/lib/kb";
const user:Actor={uid:"u1",name:"مستفيد",email:"u@example.test",createdAt:0,role:"beneficiary"};
const other:Actor={...user,uid:"u2"};
const staff:Actor={...user,uid:"s1",name:"موظف التجارة",role:"agency",entityId:"mc"};
const wrong:Actor={...staff,entityId:"moh"};
const d:Draft={kind:"inquiry",subject:"استفسار عن نشاط",body:"أرغب في الاستفسار عن إجراءات النشاط التجاري",entityId:"mc",region:"الرياض",city:"الرياض",audience:"business",attachments:[]};
const now=1_000_000;
let r=createRequest(d,user,now);
assert.equal(REGIONS.length,13);
assert(canRead(r,user));assert(canRead(r,staff));assert(!canRead(r,other));assert(!canRead(r,wrong));
assert.throws(()=>actOnRequest(r,wrong,{type:"reply",note:"test"}));
assert.throws(()=>actOnRequest(r,user,{type:"approve",note:"test"}));
assert.throws(()=>createRequest(d,staff));
assert.throws(()=>validateDraft({...d,entityId:"invented"}));
assert.throws(()=>validateDraft({...d,region:"غير موجود"}));
assert.throws(()=>validateDraft({...d,body:""}));
assert.throws(()=>validateDraft({...d,kind:"__proto__" as Draft["kind"]}));
r=actOnRequest(r,staff,{type:"start"},now+1);
r=actOnRequest(r,staff,{type:"request_info",note:"وضح النشاط"},now+2);
assert.equal(r.status,"needs_info");
assert.throws(()=>actOnRequest(r,other,{type:"resubmit",note:"متجر"}));
r=actOnRequest(r,user,{type:"resubmit",note:"بيع كتب"},now+3);
assert.equal(r.status,"in_progress");
r=actOnRequest(r,staff,{type:"close",note:"تم توضيح الإجراءات"},now+4);
assert.equal(r.status,"closed");assert.equal(r.events.length,5);assert.equal(r.version,5);
assert.throws(()=>actOnRequest(r,staff,{type:"start"}));
let permit=createRequest({...d,kind:"permit"},user,now);
assert.throws(()=>actOnRequest(permit,staff,{type:"approve"}));
permit=actOnRequest(permit,staff,{type:"approve",note:"موافقة تجريبية"},now+1);
assert.equal(permit.certificate?.demo,true);assert(permit.certificate?.number.startsWith("DEMO-"));
let overdue=createRequest(d,user,now);
assert.throws(()=>actOnRequest(overdue,user,{type:"escalate"},now+1));
overdue=actOnRequest(overdue,user,{type:"escalate"},overdue.dueAt+1);
assert(overdue.escalated);assert.throws(()=>actOnRequest(overdue,user,{type:"escalate"},overdue.dueAt+2));
const service=SERVICES.find(s=>s.requirements.some(r=>r.kind==="document"))!;
assert(requiredDocuments({kind:"license",serviceId:service.id}).length>0);
assert.throws(()=>validateDraft({...d,kind:"license",entityId:service.entityId,serviceId:service.id}));
assert.throws(()=>validateAttachments([{id:"x",name:"bad",mime:"text/html",data:"data:text/html;base64,YQ==",size:1,requirementId:""}]));
console.log("PASS: routing, 13 regions, ownership, agency isolation, lifecycle, required documents, certificate marking, escalation and validation");

